<a href="https://colab.research.google.com/github/vaishnavi64/Projects/blob/main/WISE_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/survey_lung_cancer.csv')
data

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [ ]:
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [ ]:
data.tail()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [ ]:
data.shape

(309, 16)

In [ ]:
data.describe()

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
count,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000
mean,62.673139,1.563107,1.569579,1.498382,1.501618,1.504854,1.673139,1.556634,1.556634,1.556634,1.579288,1.640777,1.469256,1.556634
std,8.210301,0.496806,0.495938,0.500808,0.500808,0.500787,0.469827,0.497588,0.497588,0.497588,0.494474,0.480551,0.499863,0.497588
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,62.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000
75%,69.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,87.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [ ]:
data.describe(include = 'all')

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
count,309,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309
unique,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES
freq,162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270
mean,NaN,62.673139,1.563107,1.569579,1.498382,1.501618,1.504854,1.673139,1.556634,1.556634,1.556634,1.579288,1.640777,1.469256,1.556634,NaN
std,NaN,8.210301,0.496806,0.495938,0.500808,0.500808,0.500787,0.469827,0.497588,0.497588,0.497588,0.494474,0.480551,0.499863,0.497588,NaN
min,NaN,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,NaN,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
50%,NaN,62.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,NaN
75%,NaN,69.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN
max,NaN,87.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [ ]:
data = data.drop(columns = ['YELLOW_FINGERS','PEER_PRESSURE','CHRONIC DISEASE','ALCOHOL CONSUMING','ANXIETY'])
data

,GENDER,AGE,SMOKING,FATIGUE,ALLERGY,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,1,2,2,2,2,2,YES
1,M,74,2,2,2,1,1,2,2,2,YES
2,F,59,1,2,1,2,2,2,1,2,NO
3,M,63,2,1,1,1,1,1,2,2,NO
4,F,63,1,1,1,2,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,2,1,1,2,2,2,1,YES
305,M,70,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,2,2,2,1,1,2,YES
307,M,67,2,2,2,1,2,2,1,2,YES
308,M,62,1,2,2,2,1,1,2,1,YES

In [ ]:
data = data.drop(columns = ['ALLERGY '])
data

,GENDER,AGE,SMOKING,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,2,2,2,2,YES
1,M,74,2,2,1,1,2,2,2,YES
2,F,59,1,2,2,2,2,1,2,NO
3,M,63,2,1,1,1,1,2,2,NO
4,F,63,1,1,2,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,2,1,2,2,2,1,YES
305,M,70,2,2,2,2,2,1,2,YES
306,M,58,2,1,2,2,1,1,2,YES
307,M,67,2,2,1,2,2,1,2,YES
308,M,62,1,2,2,1,1,2,1,YES

In [ ]:
data = pd.get_dummies(data)
data

,AGE,SMOKING,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,GENDER_M,LUNG_CANCER_NO,LUNG_CANCER_YES
0,69,1,2,2,2,2,2,2,0,1,0,1
1,74,2,2,1,1,2,2,2,0,1,0,1
2,59,1,2,2,2,2,1,2,1,0,1,0
3,63,2,1,1,1,1,2,2,0,1,1,0
4,63,1,1,2,2,2,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,2,1,2,2,2,1,1,0,0,1
305,70,2,2,2,2,2,1,2,0,1,0,1
306,58,2,1,2,2,1,1,2,0,1,0,1
307,67,2,2,1,2,2,1,2,0,1,0,1
308,62,1,2,2,1,1,2,1,0,1,0,1

In [ ]:
data = data.drop(columns = ['GENDER_F','LUNG_CANCER_NO'])
data

,AGE,SMOKING,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M,LUNG_CANCER_YES
0,69,1,2,2,2,2,2,2,1,1
1,74,2,2,1,1,2,2,2,1,1
2,59,1,2,2,2,2,1,2,0,0
3,63,2,1,1,1,1,2,2,1,0
4,63,1,1,2,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...
304,56,1,2,1,2,2,2,1,0,1
305,70,2,2,2,2,2,1,2,1,1
306,58,2,1,2,2,1,1,2,1,1
307,67,2,2,1,2,2,1,2,1,1
308,62,1,2,2,1,1,2,1,1,1

In [ ]:
target = data['LUNG_CANCER_YES']

predict = data.drop(columns = ['LUNG_CANCER_YES'])

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
predict = ss.fit_transform(predict)

In [ ]:
predict[5]

array([ 1.50382491, -1.13529242,  0.6968335 ,  0.892475  ,  0.85220712,
        0.74873631, -0.94029056, -1.12047956, -1.04978132])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(predict, target, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr_predicted = lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(lr_predicted, y_test))

0.8709677419354839

In [ ]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state = 0)
svm.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = svm.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8387096774193549

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
naive_bayes = GaussianNB()
naive_bayes.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = naive_bayes.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8548387096774194

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8225806451612904

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
criterion = 'gini'
decision_tree = DecisionTreeClassifier(criterion=criterion)
decision_tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = decision_tree.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8548387096774194

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
criterion = 'gini'
random_forest = RandomForestClassifier(criterion=criterion)
random_forest.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = random_forest.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8387096774193549